env:
    MANIFEST: https://github.com/ArrowOS/android_manifest.git -b arrow-13.1
    DEVICE: RMP6768
    OEM: realme
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifests.git
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: arrow_$DEVICE-userdebug
    OUTPUT: A*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[4251fe546ca8b91f7018c64fb78ef4b575b534b974cba0af1f19b8fc59a21afe9851da3db466a4b03400f11b2d836022]
    URI: 
    ROM_U: 0

task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
