env:
    MANIFEST: https://github.com/CherishOS/android_manifest.git -b tiramisu
    DEVICE: RMP6768
    OEM: realme
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifests.git
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: cherish_$DEVICE-userdebug
    OUTPUT: C*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[b9ec58e05fc4de856c1012122b6e809b18cbe98ad14f82ed9434e1fde2a8cf519c22b1a3ef177b13c0e3f68c605e64ec]
    URI: https://abdullah.al-noman.workers.dev/0:/ccache3.tar.gz
    ROM_U: 1

task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
