#!/bin/bash

cd /tmp
rm ccache.tar.gz
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

wget https://github.com/Sushrut1101/GoFile-Upload/raw/master/upload.sh
chmod +x upload.sh
./upload.sh ccache.tar.gz

if [ "$ROM_U" == "1" ]; then
cd ~/work/out/target/product/$DEVICE
ls
./upload.sh $OUTPUT
./upload.sh recovery.img
fi
